### ISSUE TITLE
Live store hourly backup

### ISSUE THREAD

**Issue by asim** [m3o/dev#123]
We need an automated backup for the store data. We likely need some sort of backup service which takes hourly snapshots of the deltas and puts them somewhere from where we can restore. 

- Write a backup service to automate an hourly backup of all databases
- Wrote the backups in github large file system or similar
- Test a restore to ensure the backups work
- Verify the backup after its snapshotted to ensure we got all the data

**Comment by domwong** [comment]
#276 is the mVP of this
