### ISSUE TITLE
Account Login Redirect

### ISSUE THREAD

**Issue by asim** [m3o/dev#130]
Current Experience

1. I am on web.micro.mu and click Login link
2. I then sign-in and get directed to the account settings page
3. I then click back to go to web.micro.mu

Ideal experience

1. I click Login link and account.micro.mu makes reference to the "referer"
2. I sign-in and account.micro.mu redirects me to the "referer"

**Comment by asim** [comment]
Actually would still like this to work when possible.

**Comment by domwong** [comment]
closing since we don't have a web experience yet.
