### ISSUE TITLE
Local -> Production story

### ISSUE THREAD

**Issue by domwong** [m3o/dev#162]
Make sure the developer flow from local development to production (m3o) is seamless

**Comment by crufter** [comment]
I believe this is best explained by an m3o doc in dev.m3o.com. What do you think?

**Comment by domwong** [comment]
@crufter yes I think basically what we have left to do is 
- make sure the commands work on local and staging
- document them for users

It should be that the only thing user's need to do to get on to the platform is `micro signup` and then everything else is the same e.g. `micro login`, `micro run`, etc.
