### ISSUE TITLE
Reevaluate the "special" nature of server and platform environments

### ISSUE THREAD

**Issue by crufter** [m3o/dev#193]
Services ran in `server` and `platform` environments run in the namespace of `go.micro` while other in other envs their namespace matches the namespace name.

Somewhat related doc.
https://gist.github.com/crufter/7dd99119aa4ee972201c90d90c1d634a#problem--repro

No hard reason for this apart from the gut feeling that this will cause pain later and the dislike for special exceptions.

**Comment by asim** [comment]
One other note to add to this. Micro needs to move server to local because intutively your "local" development environment is just that. We know this is a v3 thing.

When I say

```
micro env local
```

It feels more right than

```
micro env server
```

What is server? Where is the server? I think we agree anyway.

**Comment by crufter** [comment]
Yes I do agree on that point entirely. Local might be renamed "framework" perhaps or "zero-dep", or "none" even, "process". Just some ideas.

**Comment by asim** [comment]
Think we've addressed this by using "local" and "platform"
