### ISSUE TITLE
Migrate from micro/cli to spf13/cobra

### ISSUE THREAD

**Issue by domwong** [m3o/dev#211]
`micro/cli` is a fork of `urfave/cli` which is pretty unwieldy to use and has some "quirks" to behaviour. It probably makes sense at some point to move to `spf13/cobra`. 

However, as part of such a migration we would need to look at how we support plugins because they use `micro/cli` for commands and flags. Ideally we would provide a migration path that supports a seamless transition with no code changes required on the part of the plugins.

**Comment by vtolstov** [comment]
i'm against of cobra. Don't "move", but provide as plugins flag parsers

**Comment by asim** [comment]
We will move for our micro/micro binary and go-micro will remove flag and env var parsing most likely. This will means adding env vars and flags as a user requirement will either be non essential or driven through some different means. This is necessary to evolve the software. We've gonr as far as we can with urfave/cli and we do not want to maintain a fork.

**Comment by domwong** [comment]
@vtolstov do you have any particular objections against the `cobra` library itself?

**Comment by vtolstov** [comment]
@asim - this is good case
@domwong i don't want to bloatware micro more when it now

**Comment by asim** [comment]
No longer using the fork, now back to urfave/cli/v2. Unless there's any objections, we should stick with it. A refactor to Cobra in v3 doesn't make sense. Maybe v4.
