### ISSUE TITLE
Add dependency injection for handlers

### ISSUE THREAD

**Issue by asim** [m3o/dev#220]
Inject each package in go-micro into the context so they are available in handlers. This is so that each handler does not need its own fields to access these types:

```
	post.RegisterPostsHandler(service.Server(), &handler.Posts{
		Store:  service.Options().Store,
		Client: service.Client(),
	})
```

becomes

```
st, ok := store.FromContext(ctx)
```

We can use a wrapper to inject the pre-initialised options within a service

**Comment by domwong** [comment]
closed as we now just import from service/store|config|etc
