### ISSUE TITLE
micro namespace crud

### ISSUE THREAD

**Issue by domwong** [m3o/dev#226]
Add support for `micro namespace` crud actions

**Comment by crufter** [comment]
Moved this to Blocked, needs some doc about auth/namespace/project etc so we understand it,

**Comment by ben-toogood** [comment]
This was added in https://github.com/micro/micro/pull/1000 however the CLI commands were removed before merge.

**Comment by domwong** [comment]
Put on the backburner while we only have a single namespace per m3o user.
