### ISSUE TITLE
Run local code on m3o

### ISSUE THREAD

**Issue by domwong** [m3o/dev#231]
Implement `micro run .` so that it can package and upload the source code to either the build service or through the runtime. This is quite simply a Source.Upload/Download endpoint (simpler than the previous server.File endpoint) which streams chunks of a tarball up and downstream. The endpoint can live on the Runtime or on the Build service.

Ideally you go from source > build > running but the build part is totally hidden from you. In this case the source is either uploaded to the runtime which kicks off a build or sent to the build service then triggers the run. It is likely that its easier for the micro run to hand off to the runtime and let it manage the lifecycle of the source code so that it can trigger the build automatically and deploy when that build is ready.

- Add Source.Upload/Download endpoint to runtime
- `micro run .` will package a tarball and upload to runtime
- Runtime will store the tarball in store or wherever related
- In the current world source will be pulled from an endpoint in the cell
- Future world, runtime kicks off a build and then pulls the appropriate runtime build e.g binary or container image
- Potentially aes256 encrypt the tarball before storing so that its encrypted at rest

**Comment by crufter** [comment]
Related half (or less) finished PR we put away because it's a beast and we need to think about: https://github.com/micro/micro/pull/1125
