### ISSUE TITLE
LOG: Failed start error visibility

### ISSUE THREAD

**Issue by asim** [m3o/dev#244]
Found this issue today

```
asim@penguin:~/src/github.com/micro/examples/greeter$ micro env set platform
asim@penguin:~/src/github.com/micro/examples/greeter$ micro api --handler=api
{"id":"go.micro.client","code":408,"detail":"context deadline exceeded","status":"Request Timeout"}
```

Resolved by

```
micro env set local
```

It was unclear to me the environment setting was an issue. Better visibility into the failure would help.

**Comment by domwong** [comment]
@asim don't think this is an issue now right? Especially given that we've nuked `local`

**Comment by asim** [comment]
Yea no longer an issue.
