### ISSUE TITLE
Add email to /subscribe 

### ISSUE THREAD

**Issue by asim** [m3o/dev#260]
Add email as part of the subscription on https://m3o.com/subscribe so the email is tracked through to the subscription. In stripe we want to see subscriptions correlated to an email address, otherwise we have absolutely no idea who subscriptions are for.

If the user is doing `micro login`, specifying an email and we're correlating that to check if they have a subscription, we can at the very least set `/subscribe?email=foo@bar.com` so we can embed in the stripe signup. This may also allow us to send confirmation email/invoices via stripe immediately rather than generating ourselves.

This should basically be done at time of creating the customer. Right now we do not do this.

**Comment by crufter** [comment]
Email should be tracked in the subscription as subscription creation happens in the backend. https://github.com/m3o/services/blob/master/signup/handler/signup.go#L329

Only the payment method is created on the frontend.
