### ISSUE TITLE
Backup snapshots of cockroach to s3 scaleway storage

### ISSUE THREAD

**Issue by asim** [m3o/dev#276]
We're running cockroachdb for persistence. From an infrastructure perspective we should backup cockroach in the event of cluster failure or infrastructure failure. 

https://www.cockroachlabs.com/docs/stable/backup.html

1. Backup full nightly snapshot and incremental hourly to scaleway s3 object storage (upto 75gb for free)
2. Test a restore to a separate cluster once per week to ensure backups work
3. Automate any backup and restore functionality so during disaster recovery there is a playbook rather than panic

**Comment by domwong** [comment]
backup and restore https://github.com/m3o/services/tree/master/cockroachdb
