### ISSUE TITLE
Move GA tracking into alert service

### ISSUE THREAD

**Issue by asim** [m3o/dev#294]
The GA tracking info should live in the alert service rather than be baked into micro.

This highlights a design idea, which is to say, companies running a platform of their own could be running signup/alert and other things for themselves and we could let "platform" be something they can define the endpoint for. Making it configurable is an interesting idea.

Also Uber's recent post on DOMA https://eng.uber.com/microservice-architecture/ highlights the idea of "Providers" which we've explored before. The idea that something can register with a service if it honours a "Provider" interface and is then triggered when necessary. This pattern could proof useful in long term.

**Comment by crufter** [comment]
The reason we decided to not have it in our alerting service is to use GA as a fallback mechanism in case our platform is down/behaving funky. Does this reason not stand anymore?

**Comment by asim** [comment]
I think if we're using uptime robot then we'll know when the platform is down. We probably have to separate what is application error reporting to actual alerting of something being down.
