### ISSUE TITLE
Micro build service

### ISSUE THREAD

**Issue by asim** [m3o/dev#299]
It's clear that we're not going to escape the need for reproducible builds. Taking source code and running it is a nice hack but once it hits the infrastructure you need something that can be autoscaled and has sub millisecond start times across restarts. This means we need to prebuild.

## Usage

CLI commands

```
# build sends source to the build service
micro build [source]
# checks for the build before running source
# otherwise kicks off a build before running
micro run [source]
```

Build service takes source, builds a binary, container or whatever artifact and stores it in a blob store. Runtime checks for a build for its particular runtime e.g `Runtime: DefaultRuntime.String()` aka Runtime: local, Runtime: kubernetes, then pulls it and runs it.

## Requirements

Right now it's unclear if this is a feature that gets built into micro or lives externally and we simply refer to a location for the image/binary. 

What are our needs?

1. Take the source code and upload it somewhere like the store
2. Trigger a build with the build service that pulls the code and creates an artifact
3. Store the artifact in an object registry aka s3 or build a docker image that can be pulled
4. Runtime pulls the artifact based on what the underlying runtime is

Things to consider

1. How do we continue support for running `micro run [git url]` and `micro run [local dir]`
2. How do we create something that operates across local, kubernetes and future runtimes like wasm
3. Is this a build service that exists as part of OSS or do we simply right a service in m3o/services and worry about it later

## Notes

Pivotal and now Tanzu, host to SpringCloud is the perfect example of a build service https://docs.pivotal.io/build-service/0-1-0/

H2O also had a build service https://github.com/hailo-platform/H2O/tree/master/build-service

**Comment by vtolstov** [comment]
> What are our needs?
1. Use mostly wants versioned stources, how to deal with that? I think that best is to allow put zip/tar and also git interface 
(https://github.com/src-d/go-git provides backends so you can store on s3)
3. I think that create docker image and store it in you registry that can be near you platform and allow to speedup pull

**Comment by asim** [comment]
1. go-git appears to only operate like a client, if we could figure out how to make it a server with the pluggable backend we can put things into the micro store and then pull from there, so git tarballs fully uploaded and then provided back
2. how does the build service put it in a registry?

**Comment by vtolstov** [comment]
1. based on go-git somebody create server for ex: https://github.com/euforia/go-git-server
2. docker push can put container to user registry
