### ISSUE TITLE
Populate owner/group in runtime services

### ISSUE THREAD

**Issue by asim** [m3o/dev#307]
The person who runs a service should be recorded when passing a service through to the runtime

```
$ micro status
NAME                                    VERSION SOURCE                                                  STATUS                  BUILD   UPDATED METADATA
m3o/services/alert                      latest  github.com/m3o/services/alert                           running                 n/a     unknown owner=n/a,group=n/a
m3o/services/api/client                 latest  github.com/m3o/services/api/client                      running                 n/a     unknown owner=n/a,group=n/a
m3o/services/events                     latest  github.com/m3o/services/events                          running                 n/a     unknown owner=n/a,group=n/a
```

owner/group (may be renamed) would be populated so we know "janos" of the "admin" group started the service

**Comment by domwong** [comment]
Speaks to needing a proper firehose of events so that we can construct audit trails. 

https://github.com/m3o/dev/projects/11#card-43274984

**Comment by asim** [comment]
Sounds like a version of the platform events service for h2. Could start by making all the core services pump out events and just write an audit or events service in m3o repo for our own needs.

**Comment by crufter** [comment]
https://github.com/micro/micro/pull/1240

**Comment by asim** [comment]
Done
