### ISSUE TITLE
Signup text updates

### ISSUE THREAD

**Issue by domwong** [m3o/dev#326]
Current flow

```
micro signup
Enter email address: me@domwong.com
We have sent you an email with a one time password. Please enter here: *****
Please enter your password: 
Please verify your password: 
Please go to https://m3o.com/subscribe?email=me@domwong.com and paste the acquired payment method id here: ****
Successfully logged in.
```

"Please enter your password" should probably be something like "please create a new password" or similar as it's somewhat confusing because in the previous step it asks for a password from the email.

**Comment by crufter** [comment]
I think we should probably call the email OTP verification code given that it's a more widely known terminology.
