### ISSUE TITLE
Change go-micro/runtime from CRUD to Run/Kill/Update/Status

### ISSUE THREAD

**Issue by asim** [m3o/dev#339]
The go-micro/runtime has inherited a CRUD api but the CLI commands for micro are run/kill/update/status and the go-micro/runtime should likely reflect the same behaviour. This additionally allows the runtime.Status endpoint to return a []Status slice rather than service slice which lets us define status at that level rather than baking it into service metadata.

**Comment by domwong** [comment]
closing in favour of #513
