### ISSUE TITLE
Scaling - investigation

### ISSUE THREAD

**Issue by domwong** [m3o/dev#349]
How does the platform currently scale? 
- can we do horizontal scaling of things like network service to cope with increases in traffic? 

Understand the current behaviour and then improve - target should be that we can horizontally scale each and every core/m3o service to cope with increased traffic

**Comment by domwong** [comment]
Let's write down our current status and scaling approach here https://github.com/m3o/dev/tree/master/design

**Comment by asim** [comment]
This scaling doc now exists https://github.com/m3o/dev/blob/master/design/platform/scaling.md

The PR proposed has not yet factored in current usage so horizontal autoscaling would increase capacity even when we don't need it. Ideally we should only scale once at 85% or more or try to oversubscribe. Now we have metrics and kubernetes as kubectl top nodes, we should have a look. But there's a separate issue to investigate knative for scale to zero where customers services are idle.
