### ISSUE TITLE
Strip external dependencies from go-micro/micro

### ISSUE THREAD

**Issue by asim** [m3o/dev#350]
External deps like etcd not only bloat go-micro and micro but they add potential breakages upstream we have no way of controlling. In the new world of v3 we run a platform and its only that platform which uses the external deps we care about like etcd, nats and cockroachdb.

The plan: 

- We move all external plugins to go-plugins and version them independently. 
- Plugins are included at build time in profiles that group specific deps together
- Platform is a profile only we build as a separate binary/docker image for ourselves
- Kubernetes is a profile we define for OSS usage so we are complete in usage for local/kubernetes

The micro/micro image remains pure and clean with no platform profile. Basically OSS. We create a new micro/platform image for our own use and run using a separate github action.

Profiles/plugins get dropped into a "package main" file alongside main.go called profiles.go or plugins.go.

**Comment by vtolstov** [comment]
good plan
mostly one suggestion: go-plugins is really huge and with go.mod stuff not so usable too. i'm prefer to split them to go-plugins-store go-plugins-server and so. need to decide

**Comment by asim** [comment]
Done. Waiting on platform image PR to be finished but otherwise go-micro is stripped https://github.com/micro/micro/pull/1334
