### ISSUE TITLE
Share your namespace with upto 5 users

### ISSUE THREAD

**Issue by asim** [m3o/dev#356]
We want to deliver a tiered pricing model in the future Developer > Team > Enterprise. Part of that is understanding how features tiering works and the fact that you don't give it all away in one tier because you need to scale the value capture with the usage.

On the developer tier we want to enable sharing of your namespace with up to 5 people (the same as the number you can invite as referrals). Basically this sizes up to 5-6 engineers all paying independently but working in coordination.

Separately we will introduce a team based pricing tier in future that adds additional features along with SLAs.

Ideally sharing your namespace operates much like invites, a service which manages the access and the people you've shared with. Maybe part of the invite service to specify the namespace you want to share vs just being for referrals.

**Comment by domwong** [comment]
In this sharing mode does each developer get access to any other namespaces or just this single shared namespace?

**Comment by asim** [comment]
Each developer when signing up, continues to have their own unique namespace, but if they are invited to someone else's namespace that is effectively a new "scope" within their account.

**Comment by domwong** [comment]
Cool. Before anyone commences work can we please spec out what the experience looks like in that case? 

- What does the invite flow look like?
- Once enabled a user only needs some namespace switching command (` micro namespace set foo` or similar) and then everything works the same?

**Comment by asim** [comment]
I think Janos is going to spec something out. 

Assuming the user experience is `micro invite ...` to share. Person gets an email to indicate thats occurred (probably the same for referrals but a different endpoint).  If its still user config then `micro user namespace {set, add, list} ...` 

1. User does `micro platform invite --email` to invite a user to their namespace
2. User receives an email to that affect
3. User switches to the namespace `micro user config set namespace ...`
4. User now has access or may have to reauthenticate to issue themselves with a token that has the right scopes

**Comment by crufter** [comment]
Yeah I'm cooking up a short doc now that we can comment and collab on.

**Comment by domwong** [comment]
Closing this in favour of https://github.com/m3o/dev/issues/395
