### ISSUE TITLE
Max number of services per namespace

### ISSUE THREAD

**Issue by asim** [m3o/dev#359]
We need to define a "fair usage" policy that caps the number of services and usage per customer while on the developer tier. $35/month does not mean infinite resources.

Define a cap on the number of services per namespace as a configurable value and cap it at 20 services. Assuming 1 instance per service at 50mb each that's 1gb of memory usage for $35/month including the additional resources required.

We'll define fair usage in the terms and conditions for now.

**Comment by domwong** [comment]
Moving to quota based #539
