### ISSUE TITLE
Subscription cancellation

### ISSUE THREAD

**Issue by domwong** [m3o/dev#371]
Currently when a user cancels their subscription (either via us or through the self service stripe page) we don't do anything else.

We should handle the cancellation properly by:
- keeping their account live until end of the billing period
- once billing period is completed we should deactivate their account (not delete), and kill their namespace and any other relevant resources

We should also generate an alert for us (probably a simple post to a slack channel) to inform us of the cancellation so that we can do some in person follow up to see if we can get some feedback or even turn it around and get them to stay.

**Comment by asim** [comment]
Janos was added as an additional user to my namespace. I used the following steps to remove him

- Cancel stripe "M3O Additional Users" susbcription for asim@aslam.me
- Delete dobronszki@gmail.com from stripe under Subscriptions and Customers
- Delete dobronszki@gmail.com from auth with `micro auth delete account dobronszki@gmail.com`
- Delete dobronszki@gmail.com from invite service using `
  * micro store delete --table invite dobronszki@gmail.com`
  * micro store delete --table invite namespace-count/trump-disburse-gradation/dobronszki@gmail.com
  * micro store delete --table invite user-count/asim@aslam.me/dobronszki@gmail.com
  * micro store delete --table signup namespaces/dobronszki@gmail.com

**Comment by domwong** [comment]
For now we'll prorate rather than keeping account live until end of billing period to keep things simple. 

Entrypoint is `subscriptions.Cancel` (and temporarily, cancelling via stripe portal and listening for webhook)

subscriptions service will 
- do any subs tidy up including stripe
- tidy up any child subscriptions associated, e.g. additional users. 
- fire subscription.cancelled event for every user subscription cancelled (e.g. multiple if this had additional users). Event should include if sub is parent or child

customers service will listen for subscription cancelled event.
if parent sub
- delete this user's auth account 
- delete the customer
- call namespaces.Delete
- fire customers.deleted event
if child sub 
- delete the customer
- fire customers.deleted event

namespace.Delete will 
- delete any namespaces they own 
- delete any auth rules for the namespace 
- delete any remaining auth accounts in this namespace. 

Other services will need to listen to customers.deleted event and handle their own processing. e.g. invite service can clear invite counts etc. signup service can do any clean up required. etc

**Comment by domwong** [comment]
Also a question mark about what to do with the user's token . They could still have a valid token, we don't explicitly revoke a token using some block list.
