### ISSUE TITLE
Dynamic commands do not support --help

### ISSUE THREAD

**Issue by asim** [m3o/dev#375]
When I typed `micro invite --help` it threw the following error

```
Error querying registry for service invite --help: {"Id":"go.micro.client","Code":500,"Detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8000: connect: connection refused\"","Status":"Internal Server Error"}
```

I think maybe help becomes a reserved keyword? Because it would be useful to out that. The same when I try get any endpoint like `micro invite create --help`. I'd like to know what the inputs are to the service and the outputs. We can simple pull that from the registry and output in a formatted way.

**Comment by ben-toogood** [comment]
Did you have the server running / have the correct env set? It looks like it tried to lookup the invite srv but couldn't connect to the local registry.

**Comment by asim** [comment]
```
$ micro env set platform
$ micro invite --help
Error querying registry for service invite: {"Id":"go.micro.client","Code":500,"Detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8000: connect: connection refused\"","Status":"Internal Server Error"}
```
