### ISSUE TITLE
Delete old packages from github package registry

### ISSUE THREAD

**Issue by asim** [m3o/dev#378]
Find a way to delete all these https://github.com/m3o/services/packages

May work with the api https://docs.github.com/en/packages/publishing-and-managing-packages/deleting-a-package#deleting-a-version-of-a-private-package-with-graphql

Unclear how to do it as it does not seem supported through the UI at this time.

**Comment by domwong** [comment]
You can't delete public packages https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/deleting-a-package#about-public-package-deletion
