### ISSUE TITLE
Micro v2 to v3 migration guide (when v3 final is released)

### ISSUE THREAD

**Issue by asim** [m3o/dev#389]
When we have stability and v3 final is released as part of that we should release a migration guide. This helps hold on to existing users. The ideal scenario is to take some v2 services and just upgrade the go mod, see what breaks and then include that in a migration guide.

**Comment by crufter** [comment]
We could ask Arthur to tell us about his experiences.

**Comment by asim** [comment]
Guide is done by Ben
