### ISSUE TITLE
Removing any leaking go-micro reference for users micro/service

### ISSUE THREAD

**Issue by asim** [m3o/dev#391]
Users of micro should not be exposed to go-micro. Go-micro is now an internal building block for micro itself. In this case, we have the opportunity to provide drastically simpler packages in micro/service so that the developer can move fast. 

- Remove any user exposed references to go-micro in micro/service.
- Anywhere the abstraction is convoluted we rethink it e.g go-micro/metadata becomes micro/service/context

**Comment by ben-toogood** [comment]
I know we don't want the user having to import things like auth.Account, store.Record from go-micro. What's your opinion on the options @asim? I think having duplicate / alias structs is manageable but i'm concerned that so many options would be hard to maintain, e.g. the auth package alone has 23 options.

**Comment by ben-toogood** [comment]
Token is a public function in the auth package and it returns a go-micro/auth.Token object. In cases like this where porting the Token struct over would create a name conflict (this isn't an issue in go-micro because the Token function is nested within the auth interface), which object should I rename?

**Comment by asim** [comment]
I think the key thing to understand here is, what's the surface area of an API that a user needs versus what we need internally. Go-micro should be used internally for our own purposes (e.g runtime agnostic, pluggable interfaces). We have taken a short cut by simply lifting the defaults/public functions and putting them in Micro but what we should think of the service library as a new abstraction layer that's simpler. So I think its ok to start with limited options and functions specific to the needs of a user, and internally make use of go-micro directly.

Error definitions in micro were just a nice to have, but we don't have to maintain them, we can define entirely new sets of errors and in fact I imagine our list of errors will grow beyond go-micro. I'd say go-micro errors are purely networking related and micro will define higher level ones.

In the case of things like token, we just have to go through a process of renaming where it makes sense. Is it an AccessToken, an AccountToken, a ServiceToken? Either that or the public function gets renamed.

I don't believe we should do this as a big bang effort either. Store is one prime example of, hey the record and the options, should not require a go-micro import, what's the simplest fix? If it means duplicating them for now, fine, if there's a better or lighter weight approach let's figure it out? But it should be a user driven thing, if the go-micro way was cumbersome, is there a simpler way to use a thing like this? e.g options are actually just a struct?
