### ISSUE TITLE
sync service for distributed locking

### ISSUE THREAD

**Issue by asim** [m3o/dev#423]
go-micro has a sync interface for distributed locking and leadership election but we don't have a sync service. At some point we'll need to create a `micro sync` service so we can lock/elect since the store is non transactional.

**Comment by domwong** [comment]
Would be good to identify a use case on m3o side. Always prefer to use new features ourselves so we can shake out any quirks/problems with API etc

**Comment by asim** [comment]
This will show up once we start to see a more transactional need for the store since we have to read out a value before updating and writing. In the case of concurrent requests obviously it will require that.

**Comment by asim** [comment]
Closing for now. Let's come back to it when relevant. Want to start removing lingering issues which we're not going to tackle as "future ideas" so we don't assume they need to be done now. What's relevant will come back up later as you mention, when we see a need.
