### ISSUE TITLE
Build service updates

### ISSUE THREAD

**Issue by asim** [m3o/dev#460]
- [x] Rename builder service to build
- [x] Rename builder proto to build
- [ ] Move build proto to proto/ instead of in sub dir runtime
- [ ] Rename endpoint to Build.Source to avoid Build.Build stutter
- [ ] Add a readme to the build service (all services should have readmes)
- [x] Write the design doc for build service to describe the requirement and full implementation
- [ ] Write a user doc in github.com/micro/docs that explains its use

**Comment by domwong** [comment]
Closing this in favour of #506
