### ISSUE TITLE
Concurrent builds plus interface issues

### ISSUE THREAD

**Issue by asim** [m3o/dev#461]
https://github.com/micro/go-micro/blob/master/runtime/builder/golang/golang.go#L47

Concurrent builds are not possible with this implementation because temp dir points to a fixed directory that does not change on each invocation of os.TempDir() . The RemoveAll poses a potential issue and the creation of a "micro_build" poses another potential issue. 

It is safer to create a package/binary based on a name passed in. It is also more appropriate to have an interface that clearly allows you to understand whats happening. An interface that takes io.Reader and returns io.Reader is not helpful 
https://github.com/micro/go-micro/blob/master/runtime/builder/builder.go#L8. 

Move to using go-micro/build. Considering this is used by the runtime service not go-micro, simply stream the data from the user input to a file, then back from a file as required. This abstraction here isn't necessary.

**Comment by domwong** [comment]
Tempdir issue seems fixed in current impl. Closing in favour of #506 for interface issues
