### ISSUE TITLE
Detect a Micro service using a .mu file

### ISSUE THREAD

**Issue by asim** [m3o/dev#465]
We have significant entrypoint woes as we attempt to identify a Micro service based on a main.go file. Micro uses Go as the language to write services but that is not the definition of a Micro service. We must look to move towards defining a Micro service in our own way.

A micro service will be identified by a `service.mu` file. To start this file will simply give us the name of the service. Over time it will evolve to include more config which we can strip from main.go. The .mu file will be simple text, not json or yaml and will start with a "service [name]" in the file as the first identifier.

Every micro service generated with `micro new` will be given this at the top level e.g `micro new user` will create a user.mu file. The name of the file poses no significance, we will look to detect all .mu files so if multiple co-exist in the same directory there is no conflict.

**Comment by domwong** [comment]
How does this get used to define the entrypoint?

**Comment by asim** [comment]
To start we'll just assume the main.go is in the same directory as the .mu file but longer term we'll define "program [path/to/program]" in the file to tell us where it is, which again will just be in the current directory. The goal is to define what a "Micro" service is rather than rely on Go as that thing.
