### ISSUE TITLE
Prefix STORE to any blob related values

### ISSUE THREAD

**Issue by asim** [m3o/dev#478]
The S3_ENDPOINT value is a red herring in micro, a unique snowflake value. This should be STORE_BLOB_ADDRESS or something similar. It's otherwise deviating from the tooling's normal usage.

**Comment by domwong** [comment]
Is this talking about for the minio install script? I can't see `S3_ENDPOINT` in any part of the core micro code

**Comment by asim** [comment]
These values were directly being set with the runtime previously from what I recall, they looked to have vanished now. It now appears to be  minio-cluster after this change `s3.Endpoint("minio-cluster:9000"),` .
