### ISSUE TITLE
Create token per namespace and a separate .micro/tokens file

### ISSUE THREAD

**Issue by asim** [m3o/dev#480]
Right now switching between environments/namespaces causes some irregularities because we have a token per env. We need to move to token per namespace if login is namespace specific. We also need to separate tokens from the config so that we're not bloating it or storing sensitive credentials there.

Move tokens to .micro/tokens file. Use line per namespace/username:token in the format of namespace:username:token or something similar that provides a good standard format. Another form is micro://[env]/[namespace]/[id]/[token] which complies with the idea of account.String() => returning that format.

**Comment by crufter** [comment]
Food for though: separate files for tokens vs putting them in one file. Cons and pros?

**Comment by asim** [comment]
I think just as we have one config file, one token file to start is good. Config can be set via a -c flag to indicate where, so token file could be the same if we wanted to split it out.

**Comment by crufter** [comment]
Is it okay if said token file is also a JSON? As the token itself has 3 parts (`expiry`, `token`, `refresh-token`) I think it makes sense.

**Comment by asim** [comment]
I don't think that makes sense considering the encoded token contains all this data anyway right?
