### ISSUE TITLE
Port go-micro packages into micro/internal

### ISSUE THREAD

**Issue by asim** [m3o/dev#491]
Taking inspiration from Shay Banon (https://thedudeabides.com/articles/the_future_of_compass). We're going to officially leave behind go-micro and go-plugins. In fact I'm going to move them to my personal repo in a declaration that this was the first 4 years of solo work and micro v3 & m3o is now a team effort.

Port over anything from go-micro used in micro as micro/internal packages. As this was our infrastructure agnostic layer, we'll continue to treat it as that, anything internal maintains an interface to provide that dividing line. Our micro/service package will then be a cleanly defined library for dev UX.

**Comment by domwong** [comment]
👍  should make our lives a whole lot easier when making changes. 

This will be a relatively big change so I would ask we do the following:
- Don't just move the code, move the tests too. It'll help give us confidence in our refactor
- Make sure customer impact is reduced to a minimum by double checking, once we've moved the repo, that some example service still builds successfully against go-micro
- Have a good narrative for our users (blog post) that sets out why we're making this change. Asim has spent a lot of time amassing these users, they are all potential m3o users, let's make sure we don't burn the reputation that we have built with them

One question: should we revert the master branch of go-micro to v2 and move the v3 work that has been done to a branch? In some way we're basically saying that go-micro v3 is never going to happen so the beta work up until now is not required

**Comment by asim** [comment]
I think the last point is fair. There's a lot of changes related to v3 but at the same time we actually made some great standalone improvements. But you're right. if go-micro moves to being a personal project again, I have no plans to maintain it and I don't expect anyone else to either, so we should leave v2 as a functioning thing people can use and just declare our efforts on micro v3 as a totally standalone effort towards m3o as a platform.
