### ISSUE TITLE
Users service

### ISSUE THREAD

**Issue by domwong** [m3o/dev#540]
Reusable service for authentication to be leveraged by our customers to easily build a full end to end system with user authentication

**Comment by crufter** [comment]
So the main aspects are:

- Create a single tenant (ie each user will have to run this service in their namespace) users service
- Enable users to register by providing email, username, password
- Enable users to log in ie. create a session
- Enable service writer to resolve this session to a user (so service can do authorization)
- Enable admin to read, search amongst users

**Comment by crufter** [comment]
This is a port of an existing users service, I have only ported it to model and weeded out the rough edges: https://github.com/micro/services/pull/19/

**Comment by asim** [comment]
Done as far as we can see.

**Comment by crufter** [comment]
Next up for this line of work is multitenancy support for users and blog services, and making blog services use that service, consequently becoming multitenant too.

Once that's done we can enable people to build on top of micro (in this case run a blog with only frontend, using Micro as a backend) even without a Micro account, purely as consumers of APIs.
