### ISSUE TITLE
Platform MVP

### ISSUE THREAD

**Issue by asim** [m3o/dev#62]
# Platform MVP

Our goal is to deliver **M3O** - Micro as a Service - as a paid hosted product

## Overview

Micro provides an open source framework for microservices development. It's become a popular standard for writing distributed systems in the Cloud. However managing the complexity of Cloud has become incredibly difficult. We will offer developers a managed platform for Micro services development. By doing so they should no longer need to manage Micro themselves.

## Objectives

Offer Micro as a Platform as a Service (PaaS) for Micro services development. Remove the need for developers to use AWS, GCP or Azure directly. Just as GitHub solves Git hosting, we solve for Micro hosting.

We will deliver the following:

- Paid hosted platform for Micro services development
- Charge for additional value add services in a pay per use model
- Focus on delivering the Micro Platform as a multi-tenant platform
- Operate in invite only mode to ensure the reliability and scaling of the platform

## Benefits

What we essentially want to unlock by providing such a platform is the below outcomes:

- **Developer productivity** - Fully managed platform so developers don't have to touch infra
- **Collaboration and reuse** - Built for teams and shared ownership of services 
- **Velocity of development** - "Everything as a service" means one way of doing things

## Pricing

We will have 3 tier plan; Community, Developers and Teams.

- Community is "free" for open source projects
- Developers is "$35/month" for unlimited usage
- Teams is "$45/user/month" (post MVP)

## Dev UX

The developer experience we're expecting to deliver on this sprint is as follows.

1. Developer signs up to wait list on m3o.com
2. Email users on waitlist with signup instructions
3. Download micro and use `micro login` to signup/login
4. Direct to m3o.com/subscribe to pay for the platform
5. Use micro as you would the open source

## Actions

Focus on doing a few things really well.

- [x] Incorporate namespacing for multi-tenancy
- [x] Create a sign-up flow to pay and access the platform
- [x] Define a getting started guide for the platform
- [x] Dogfood the product to ensure it works (VERY IMPORTANT)
- [x] Onboard new developers to the platform

## Reference

- [roadmap](https://github.com/micro/development/tree/master/roadmap)
- [glossary](https://github.com/micro/development/blob/master/glossary.md)

**Comment by asim** [comment]
# Notes

Notes from Ben
 
- Identity - I think Jake is working on a plan for this atm. I think we should do a call to plan this tomorrow morning.
- Deployment Mechanism - i.e. how are devs going to deploy services to the platform. I belive Janos is working on refactoring the GH action into Go, with some minor changes we should be able to make this work for private repos also.
- Runtime Namespace - we need to decide if namespacing the runtime is necessary? If we make it so none of the namespaces can call runtime then we should be okay keeping this as is.

- A few things i'd love to do but I don't think are critical to launching MVP:
- Refactor micro web to more cleanly proxy from default home.
- Change the default go.micro namespace to just be micro
- Add the ability to invite other team members to your namespace (I think this is v1.0.1).
- Monitor / record the number of services running in a users namespace for billing purposes

**Comment by domwong** [comment]
Current (as of 18/05/2020) understanding of the MVP deliverable is

- High level features as per https://micro.mu/docs/platform.html 
- Go from code in github to running on the platform
   - Local -> cloud
- Self service
- API, CLI, Web dashboard
- Logging/Debugging of running services
   - Everything via the CLI - logs, tracing, stats
   - Web to follow later
- Services
   - Store (Cockroach)
   - Auth
   - Config
   - Pub sub (Nats)
   - Registry (etcd)
   - etc

*Billing granularity?* Ignore for now. Flat rate per customer.

*SLA?* None for now, control the influx of customers to help stability

**Comment by asim** [comment]
We appear to be on track to deliver the MVP by end of this week. Will close once done.

**Comment by asim** [comment]
Closing the platform MVP is done. Congratulations folks.
